### ISSUE TITLE
blaze-builder doesn't compile with GHC <= 7.0.4

### ISSUE THREAD

**Issue by peti** [meiersi/blaze-builder#16]
A complete build log of the build error is at http://hydra.cryp.to/build/105415/nixlog/1/raw.

Unfortunately, this issue prevents me from building `aeson` (Cc: @bos) with older compilers, which in turn breaks the builds of great many packages. Is there any chance that I could get a new release of this package on Hackage that remedies the issue?

**Comment by meiersi** [comment]
Hi Peter, thanks for the report. I'm currently on holidays and don't have
access to a computer. I can in principle prepare such a package, I wonder
what we gain by supporting such an old compiler. What are your reasons?

Best regards,
Simon
Am 24.05.2014 03:07 schrieb "Peter Simons" notifications@github.com:

**Comment by peti** [comment]
Hi Simon,

I'm not sure what you mean by "what do we gain?". We gain the ability to compile this package with an old compiler! We also gain the ability to compile a few dozen other packages that currently won't build because they directly or indirectly depend on blaze-builder. Of course, the ability to compile recent code with old compilers is not super important, and it's probably not worth jumping through hoops to achieve it, but if it can be done with a comparatively minor effort, then I think it's pretty cool to have that chance, i.e. for performance tests, etc.

Best regards,
Peter

**Comment by meiersi** [comment]
Hi Peter,

sorry for the imprecision in my question. I was wondering where and why GHC
<= 7.0.4 is still in use. If there's a good use case, and there might very
well be one, then your ticket is very much appreciated.

Best regards,
Simon

Am 24.05.2014 17:25 schrieb "Peter Simons" notifications@github.com:

**Comment by meiersi** [comment]
Closed via #21.
