### ISSUE TITLE
IsString instance for Builder

### ISSUE THREAD

**Issue by istathar** [meiersi/blaze-builder#9]
I found myself having to remove an orphaned IsString instance from **http-streams**. My bad, I didn't realize that GHC leaks instance declarations. But it was awfully useful. I simply had:

```
import Data.String (IsString, fromString)
...

instance IsString Builder where
    fromString x = Builder.fromString x
    {-# INLINE fromString #-}
```

And it made my HTTP request code quite clean. Now it's littered with `Builder.fromString` which is a bit klunky. It also led me to having to change the public examples from:

```
Streams.write (Just "Hello World\n") o)
```

to

```
Streams.write (Just (Builder.fromString "Hello World\n")) o)
```

since the type we use in **http-streams** is OutputStream Builder. Bit of a shame when we're hoping to convince people that the API is "simple" to use.

Is there any chance that you could add an IsString instance to **blaze-builder**? I gave it a quick try, but realized that given the internals there was probably a better way than the code I quoted above.

AfC

**Comment by meiersi** [comment]
Hi Andrew,

I considered adding such an instance, but didn't because it is not obvious how the `String` is encoded to a sequence of bytes. One can already see this from your example, which actually doesn't tell me whether you want your `String` to be encoded by truncating the Unicode codepoint to 8-bits (informally called the char8 encoding) or whether you want to use for example a UTF-8 encoding.

Out of experience, I would expect that you want the `char8` encoding. However, in HTTP streams this is probably not always a given; e.g., when you are manually writing a `text/html;charset-utf8` request. Therefore, I would suggest to provide additional combinators with more telling names. For example,

```
Streams.writeBS (Just "Hello World\n") o)
```

would use the proper `IsString` instance from strict bytestrings and give you the same result. What do you think?

**Comment by istathar** [comment]
@meiersi,

Where **I** was using the the IsString instance was for composing HTTP protocol headers, and that is explicitly ASCII only. So Char8 (sic) would have been fine. But you make a good point; in general people using such an Instance this are going to be feeding arbitrary literals.

For what it's worth, anyone writing a source file in anything other than UTF-8 is bonkers, which I would take to mean that any literals getting snarfed by OverloadedStrings would be UTF8. But I don't know at what point the compiler translates UTF-8 source to char codepoints; I assume it's _before_ fromString is called. That being the case, I think you can just assume Haskell Unicode chars, no?

AfC

**Comment by meiersi** [comment]
@afcowie , the type of `fromString :: String -> a` guarantees that it is feed Unicode codepoints. So, the source file encoding doesn't play a role here.

What I meant is that there are several ways how `fromString :: String -> Builder` could be implemented, which correspond to the different encodings of Unicode strings. Choosing an encoding is a decision that should be made consciously by the application developer. This is my main reason for not providing an `IsString` instance for `Builder`s. 

The second reason is that depending on the chosen encoding one wants to use a different representation of the actual literal. If you want a `char8` encoding, then you want the literal to be represented as a strict bytestring, whereas if you want a `UTF-8` encoding, then you either want the literal to be represented as a pre-encoded bytestring or a strict `Text` value. However, in both cases you _don't_ want to use an actual `String` literal. I think by not hiding these implementation choices, I'm actually doing the application developer a favour. However, I'm probably doing a poor job in the documentation to explain that to a developer.

Anyways, I still wonder why you cannot easily piggy-back on the `IsString` instances for strict bytestring and strict text values by providing ways to easily inject such values in your http-streams?

**Comment by meiersi** [comment]
Please reopen if you you'd like to pursue this discussion.

**Comment by istathar** [comment]
@meiersi Like I said above, I'm just trying to make this less ugly:

```
Streams.write (Just (Builder.fromString "Hello World\n")) o)
```

I did it with an IsString instance that called `Builder.fromString` for me. Seemed to work. You're right, I'm not considering encoding, but presumably `Builder.fromString` applied to a string literal in a Haskell source file would just work.

AfC

**Comment by meiersi** [comment]
What about introducing `writeStringUtf8 :: String -> OutputStream Builder -> IO ()` such that you can write

```
writeStringUtf8 "Hello World" o
```

this also handles encoding properly. The problem with the `IsString Builder` instance is that it conflicts with the use of overloaded string literals for `ByteString`. These literals are encoded by truncating their codepoints to one byte. This encoding is typically called the `Char8` encoding in Haskell libraries. For the string "Hello World" the UTF-8 encoding and the Char8 encoding are obviously the same. However, for a non-ASCII string they do differ. I think this difference is something that every author should think about. This difference is also the reason why I don't think having an `IsString Builder` instance is a good idea. 

With the above utility module scheme you could use the Char8 encoding for literals as follows.

```
writeByteString "Hello World" o
```
